version: '3'

services:
  bot:
    build: .
    environment:
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
    restart: always
